### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by Jonatan74268** [Jonatan74268/ExamenP2BackEnd#3]
Recuerden que el frontend es el del parcial psasado

**Comment by Peter5528** [comment]
Es el que esta en el otro repositorio?

**Comment by auribe8** [comment]
Si, deberiamos poner aqui el link aqui tambien

**Comment by AnairamFalcon** [comment]
Ah esperen dejen lo pongo

**Comment by AnairamFalcon** [comment]
https://github.com/Jonatan74268/ExamenP2FrontEnd.git
Si quieren descargarlo y probarlo en sus compus

**Comment by Jonatan74268** [comment]
Ese ya esta con los commits

**Comment by auribe8** [comment]
Ya nada mas es cuestion de correrlo al mismo tiempo

**Comment by Peter5528** [comment]
Ya lo probé, ya jaló
